import shuffle from 'lodash/shuffle';

const lists = [
  {
    title: 'TOP 5 MOVIES',
    list: [
      'The Godfather (1 and 2)',
      "Schindler's List",
      'Pulp Fiction',
      'Inception',
      'Battle Royale',
    ],
    tooltips: [
      'They are both equally good',
      '',
      '',
      '',
      'Really underrated movie. Sequel was awful however',
    ],
  },
  {
    title: 'TOP 5 PS4 GAMES',
    list: [
      'Red Dead Redemption 2',
      'God of War',
      'Uncharted 4',
      'Spiderman',
      'The Last of Us Remastered',
    ],
    tooltips: ['', '', '', "I've been playing Spiderman way too little", ''],
  },
  {
    title: 'TOP 5 SWITCH GAMES',
    list: [
      'The Legend of Zelda: Breath of the Wild',
      'Super Mario Odyssey',
      'The Legend of Zelda: Link’s Awakening',
      'Shovel Knight: Treasure Trove',
      'Super Mario Maker 2',
    ],
    tooltips: [
      '',
      '',
      '',
      'Not Switch exclusive but I just really like Shovel Knight',
      '',
    ],
  },
  {
    title: "TOP 5 CITIES I'VE VISITED",
    list: ['Singapore', 'Berlin', 'London', 'Barcelona', 'Rome'],
    tooltips: [
      'A melting pot of Asian cultures in one city. Loved it!',
      'Great restaurants, amazing beer. Really loved the zoo as well',
      'Ah, so many shops to visit. And so many world-class theater shows. Amazing city',
      'An incredible number of attractions and things to do.',
      'In Rome, history is always around you. Awesome culture',
    ],
  },
  {
    title: 'TOP 5 CITIES I WOULD LIKE TO VISIT',
    list: ['New York', 'Tokyo', 'Sidney', 'Los Angeles', 'Copenhagen'],
    tooltips: [
      '',
      'We were supposed to go to Tokyo in our honeymoon, but the trip was canceled. Indeed a place to visit once in a lifetime',
      '',
      '',
      '',
    ],
  },
  {
    title: 'TOP 5 FICTION BOOKS',
    list: [
      '1984',
      'Alchemist',
      'Lord of The Rings',
      'Brave New World',
      "Hitchhiker's Guide to the Galaxy",
    ],
    tooltips: [
      '',
      '',
      '',
      'I really like dystopia books',
      'So long, and thanks for all the fish',
    ],
  },
  {
    title: 'TOP 5 PROGRAMMING BOOKS',
    list: [
      'Clean Code',
      'The Pragmatic Programmer',
      'Code: The Hidden Language of Computer Hardware and Software',
      'The Clean Coder',
      'JavaScript: The Good Parts: The Good Parts',
    ],
    tooltips: [
      '',
      '',
      '',
      '',
      'Not really "amazing" book but I had to write something :D But this was one of the first books I\'ve read about JavaScript and I think it was one of the reasons I got excited about the language',
    ],
  },
  {
    title: 'TOP 5 GENESIS GAMES',
    list: [
      'Sonic The Hedghehog 3 / Sonic and Knuckles',
      'Sonic The Hedghehog 2',
      'Earthworm Jim',
      'Aladdin',
      'NHL 95',
    ],
    tooltips: [
      'Basically the same game. At least they were meant to be',
      '',
      '',
      '',
      'NHL 94 is usually "the best" retro hockey game that people choose, but I\'ve always liked NHL95 more. It has more speed and some things are also more polished',
    ],
  },
  {
    title: 'TOP 5 SUPER NINTENDO GAMES',
    list: [
      'Final Fantasy 6',
      'Super Mario World',
      'The Legend of Zelda: A Link to the Past',
      'Super Mario Kart',
      'Super Castlevania IV',
    ],
    tooltips: [
      "One of my favourite games of all time and absolutely one of the best experiences I've had with any game.",
      '',
      '',
      '',
      '',
    ],
  },
  {
    title: 'TOP 5 CARD GAMES',
    list: [
      'Munchkin',
      'Joking Hazard',
      'Bang!',
      'Exploding Kittens',
      'Muffin Time',
    ],
    tooltips: [
      'Sooooo many hours spent playing this with friends.',
      'Guaranteed laughs',
      '',
      '',
      '',
    ],
  },
  {
    title: 'TOP 5 NONFICTION BOOKS',
    list: [
      'The Subtle Art of Not Giving a F*ck',
      'Sapiens',
      'Permanent Record',
      'Never Split the Difference',
      'Steve Jobs',
    ],
    tooltips: [
      'Changed the way I look my life. Big recommendation',
      '',
      '',
      '',
      '',
    ],
  },
  {
    title: 'TOP 5 ARNOLD SCHWARZENEGGER MOVIES',
    list: ['Terminator 2', 'Commando', 'Predator', 'Terminator', 'Conan'],
    tooltips: ['', '', '', '', ''],
  },
  {
    title: 'TOP 5 ATTRACTIONS IN TAMPERE',
    list: ['Särkänniemi', 'Vapriikki', 'Pyynikki Tower', 'Tallipiha', 'Ratina'],
    tooltips: ['', '', '', '', ''],
  },
  {
    title: "TOP 5 CAREER CHOICES IF I WOULDN'T BE PROGRAMMER",
    list: [
      'Lawyer',
      'History Teacher/Scholar',
      'Game Designer',
      'Business',
      'Writer',
    ],
    tooltips: [
      'I was supposed to study law before I went to computer science. Especially copyright law has always interested me',
      "History has always been a dear hobby for me that I thought as my profession at some point. Don't know how I would have made my money with it...",
      'I still want to be game designer and MAYBE I will be',
      "I've always like writing fiction.",
      "Business was one of my options to study in university but fortunately I got in to computer science. I don't think I would've been great at it :D",
    ],
  },
  {
    title: 'TOP 5 ARCADE GAMES',
    list: [
      'Metal Slug 1-X',
      'Donkey Kong',
      'The Simpsons Arcade Game',
      'Virtua Cop 2',
      'Area 51',
    ],
    tooltips: [
      'Absolutely fantastic games. I had pleasure to try the original arcade cabinet in Prague',
      '',
      '',
      '',
      'Our local swimming hall had Area 51 arcade in cafe and I spent way too many marks in it',
    ],
  },
  {
    title: 'TOP 5 GUILTY PLEASURE GAMES',
    list: [
      'Dynasty Warriors 4-9',
      'Minecraft',
      'NHL 95',
      'Mad Max',
      'Far Cry 3-5',
    ],
    tooltips: [
      'I love all Warriors-games. They might be button-smashers but still sooo goood',
      '',
      '',
      "Critics didn't love the game but I did",
      '',
    ],
  },
  {
    title: 'TOP 5 COCKTAILS',
    list: [
      'Caipiroska',
      'Long Island Ice Tea',
      'Mojito',
      'Old Fashioned',
      'Rum & Coke',
    ],
    tooltips: ['', '', '', '', ''],
  },
  {
    title: 'TOP 5 PROGRAMMING LANGUAGES I WANT TO LEARN',
    list: ['Elixir (Erlang)', 'Rust', 'Golang', 'Haskell', 'Lua'],
    tooltips: ['', '', '', '', 'Especially for Pico-8'],
  },
  {
    title: 'TOP 5 NETFLIX SHOWS',
    list: [
      'The Witcher',
      'Stranger Things',
      'Tiger King',
      'Better Call Saul',
      "The Queen's Gambit",
    ],
    tooltips: [
      '',
      '',
      'I ADMIT! I enjoyed this',
      '',
      'This was total surprise how good it was',
    ],
  },
  {
    title: 'TOP 5 SODAS',
    list: [
      'Pepsi Max',
      'Dr. Pepper',
      'Mountain Dew',
      'Coca-Cola',
      'Hartwall Jaffa',
    ],
    tooltips: [
      'Pepsi Max is actually the only soda I drink regularly',
      '',
      '',
      '',
      'Better than Fanta',
    ],
  },
  {
    title: 'TOP 5 MARVEL MOVIES',
    list: [
      'Thor: Ragnarök',
      'Avengers: Infinity War',
      'Guardians of the Galaxy',
      'Black Panther',
      'Ant-Man',
    ],
    tooltips: [
      'Great action and funny as hell. Can not wait for the next Thor-movie',
      'Both movies',
      '',
      '',
      '',
    ],
  },
  {
    title: 'TOP 5 ICE CREAM FAVOURS',
    list: [
      'Bourbon Vanilla',
      'Cookie Dough',
      'Tiger',
      'Licorice',
      'Mint-Chocolate',
    ],
    tooltips: [
      '',
      '',
      'Vanilla ice cream with orange stripes',
      '',
      'Fun fact: I hate chocolate ice cream but I like mint-chocolate',
    ],
  },
  {
    title: 'TOP 5 RETRO CONSOLES',
    list: [
      'Genesis (Mega Drive)',
      'Super Nintendo',
      'NES',
      'Playstation',
      'Game Boy Color',
    ],
    tooltips: ['The first console I ever owned', '', '', '', ''],
  },
  {
    title: 'TOP 5 STAR WARS MOVIES',
    list: [
      'Star Wars Episode VI: Return of the Jedi ',
      'Star Wars Episode IV: A New Hope',
      'Star Wars Episode V: The Empire Strikes Back',
      'Rogue One: A Star Wars Story',
      'Star Wars Episode VII: The Force Awakens',
    ],
    tooltips: [
      '',
      '',
      '',
      '',
      'I was so happy to see this movie at its premiere. Really sad how the rest of the trilogy ruined it for me.',
    ],
  },
  {
    title: 'TOP 5 DISNEY MOVIES',
    list: ['Lion King', 'Aladdin', 'Hercules', 'Big Hero 6', 'Pocahontas'],
    tooltips: ['', '', '', '', ''],
  },
  {
    title: 'TOP 5 POKEMONS',
    list: ['Mewtwo', 'Charizard', 'Alakazam', 'Gyarados', 'Hitmonlee'],
    tooltips: [
      'My 99 level Mewtwo dominated my childhood neighborhood Pokemon fights',
      'Pokemon Red ftw',
      '',
      '',
      '',
    ],
  },
  {
    title: "TOP 5 PHONES I'VE HAD",
    list: [
      'iPhone 11',
      'Samsung Galaxy S2',
      'OnePlus 2',
      'Nokia N71',
      'Nokia 3510i',
    ],
    tooltips: [
      "My first iPhone and the best phone I've ever had",
      'I had S8 later and it was really awful. Full of bloatware and unremovable Facebook-app. S8 was the biggest reason why I switched from Android to Apple',
      '',
      '',
      'Color screen?! Midi-ringtones!? WAP!?! Oh man, this phone was awesome in secondary school',
    ],
  },
  {
    title: 'TOP 5 COMIC BOOKS',
    list: [
      'Watchmen',
      'Sin City',
      'The Dark Knight Returns',
      'Arkham Asylum',
      'The Killing Joke',
    ],
    tooltips: [
      '',
      'All. Can not choose just one',
      '',
      'I love the art style. Maybe the most beautifully chaotic comic I know',
      '',
    ],
  },
  {
    title: 'TOP 5 EMOJIS',
    list: ['🤔', '👌', '😄', '🌝', '👾'],
    tooltips: ['🤔', '👌', '😄', '🌝', '👾'],
  },
  {
    title: 'TOP 5 FOOD DISHES',
    list: [
      'Good Meatball Pasta',
      'Sushi',
      'Pizza',
      'Pasta Carbonara',
      'Cannelone',
    ],
    tooltips: [
      '',
      '',
      'Spicy sour dough pizza or mayonnaise pizza (Oulu specialty)',
      '',
      '',
    ],
  },
  {
    title: 'TOP 5 THE LEGEND OF ZELDA GAMES',
    list: [
      'The Legend of Zelda: Breath of the Wild',
      'The Legend of Zelda: A Link Between Worlds',
      'The Legend of Zelda: Link’s Awakening',
      'The Legend of Zelda: A Link to the Past',
      'The Legend of Zelda: Ocarina of Time',
    ],
    tooltips: [
      '',
      '',
      '',
      '',
      "5th place!? I've only played Ocarica of time few hours on 3ds so I can't place it higher :/",
    ],
  },
];

export default shuffle(lists);
